---

- hosts: server
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: "{{ lookup('file', '/Users/edlining/Desktop/AWS_Credentials/terraform_ec2_key') }}"
  tasks:
  - copy:
        src: /Users/edlining/Desktop/Ansible/ansible/sfw
        dest: /tmp
        owner: ec2-user
        group: ec2-user
        mode: 0755
# bzip2 -d filename.bz2
