---

- hosts: server
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: "{{ lookup('file', '/Users/edlining/Desktop/AWS_Credentials/terraform_ec2_key') }}"
  tasks:
  - copy:
        src: /Users/edlining/Desktop/Ansible/ansible/sfw
        dest: /tmp
        owner: ec2-user
        group: ec2-user
        mode: 0755

  - yum:
      name: "{{ packages }}"
    vars:
      packages: 
      - bzip2
      - unzip
      - ncurses
      - xorg-x11-*
      - libX11-devel
      - "@Development tools"
      - libXext-devel*
      - gcc*
      state: latest
    become: yes

  - command: bzip2 -d /tmp/sfw/snes9x-1.53-src.tar.bz2

  - unarchive:
     src: /tmp/sfw/snes9x-1.53-src.tar
     dest: /tmp/
     remote_src: yes

  - name: Configuring snes source 
    command: "./configure"
    args:
      chdir: "/tmp/snes9x-1.53-src/unix/"

#  - name: make snes source
#    command: "make"
#    args:
#      chdir: "/tmp/snes9x-1.53-src/unix/"
#
#  - name: run snes9x 
#    script: /tmp/snes9x-1.53-src/unix/snes9x /tmp/sfw/DonkeyKongCountry2DiddysKongQuest.zip
# other rpms needed for X11
#sudo yum install -y gcc-c++
#sudo yum install -y libX11-devel
#sudo yum install -y fontconfig-devel
#sudo yum install -y libXcursor-devel
#sudo yum install -y libXext-devel
#sudo yum install -y libXfixes
#sudo yum install -y libXft-devel
#sudo yum install -y libXi-devel
#sudo yum install -y libXrandr-devel
#sudo yum install -y libXrender-devel
